### ISSUE TITLE
[BUG] - Damage numbers for shelling on gunlance don't show

### ISSUE THREAD

**Issue by Veidratox** [DorielRivalet/mhfz-overlay#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

All other parts of the overlay work fine, it's just the damage numbers when specifically shelling with gunlance which don't
(This includes wyvern fire)

### How often does the bug occur?

Always

### What version of the program are you using?

Latest version

**Comment by DorielRivalet** [comment]
This is due to how the game handles different sources of damage. Same reason for reflect or bombs damage not showing.
I'm closing this and opening a [feature request](https://github.com/DorielRivalet/mhfz-overlay/issues/378) for it.
What would probably need to be done is searching for another memory address for those sources of damage (since this is how the overlay reads values).

**Comment by Veidratox** [comment]
Ok ty!
